apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
spec:
  template:
    spec:
      containers:
        - name: kube-multus
          startupProbe:
            exec:
              command:
                - cat
                - /host/etc/cni/net.d/01-kube-ovn.conflist
