apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
spec:
  template:
    spec:
      containers:
        - name: kube-multus
          args:
            - "--multus-conf-file=auto"
            - "--cni-version=0.3.1"
            - "--multus-master-cni-file-name=01-kube-ovn.conflist"
            - "--multus-log-level=error"
