apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
spec:
  template:
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: kube-multus
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            # Mount OVS Socket
            - mountPath: /run/openvswitch
              name: host-run-ovs
      volumes:
        - name: host-run-ovs
          hostPath:
            path: /run/openvswitch
