apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
spec:
  template:
    spec:
      initContainers:
        - name: install-multus-binary
          image: ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
          command:
            - "cp"
            - "-f"
            - "/usr/src/multus-cni/bin/multus-shim"
            - "/host/opt/cni/bin/multus-shim"
