---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  destination:
    namespace: crossplane-system
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 2.2.0
    helm:
      releaseName: crossplane
      valuesObject:
        hostNetwork: true
        dnsPolicy: "ClusterFirstWithHostNet"
        metrics:
          enabled: true # enable to add the port definition to the deployment otherwise it binds to the port but doesn't let k8s know
