apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: ARGOCD_SERVER_HOST
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: https
  tls:
    - secretName: argocd-server-tls # do not change https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#tls-certificates-used-by-argocd-server
      hosts:
        - ARGOCD_SERVER_HOST
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/pelotech/foundation # issuer, nidhogg
    - https://charts.jetstack.io # cert-manager
    - https://kubernetes-sigs.github.io/external-dns # external dns
    - https://aws.github.io/eks-charts # alb/nlb
    - https://kubernetes.github.io/ingress-nginx # ingress-nginx
    - registry-1.docker.io/bitnamicharts # multus
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: external-dns
      server: https://kubernetes.default.svc
    - namespace: alb
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: kube-system # multus
      server: https://kubernetes.default.svc
    - namespace: nidhogg-system
      server: https://kubernetes.default.svc
    - namespace: tailscale
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - argocd
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/pelotech/foundation
    - https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    - https://awslabs.github.io/mountpoint-s3-csi-driver
    - https://backube.github.io/helm-charts
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: snapscheduler
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - argocd
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/pelotech/foundation
    - https://aws-observability.github.io/aws-otel-helm-charts
    - https://fluent.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: adot
      server: https://kubernetes.default.svc
    - namespace: fluent-bit
      server: https://kubernetes.default.svc
    - namespace: grafana-k8s-monitoring
      server: https://kubernetes.default.svc
    - namespace: loki
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - argocd
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: utils
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/pelotech/foundation
    - https://stakater.github.io/stakater-charts
    - https://charts.crossplane.io/stable
    - https://charts.fairwinds.com/stable
    - https://argoproj.github.io/argo-helm
    - https://kyverno.github.io/kyverno
    - public.ecr.aws/karpenter
  destinations:
    - namespace: reloader
      server: https://kubernetes.default.svc
    - namespace: crossplane-system
      server: https://kubernetes.default.svc
    - namespace: goldilocks
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: karpenter
      server: https://kubernetes.default.svc
    - namespace: kube-system # karpenter-dns
      server: https://kubernetes.default.svc
    - namespace: kube-node-lease
      server: https://kubernetes.default.svc
    - namespace: kubevirt
      server: https://kubernetes.default.svc
    - namespace: cdi
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - argocd
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
