---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: cilium
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: cilium
    repoURL: https://helm.cilium.io
    targetRevision: 1.14.4
    helm:
      releaseName: cilium
      parameters:
        - name: cni.exclusive
          value: "false"
        - name: cni.customConf
          value: "true"
        - name: nodeSelector
          value: 'pelo.tech/multi-home-networking: "true"'
