---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: cilium
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: cilium
    repoURL: https://helm.cilium.io
    targetRevision: 1.14.4
    helm:
      releaseName: cilium
      valuesObject:
        cni:
          exclusive: "false"
          # tunnelProtocol: ""
          tunnelProtocol: geneve
          # routingMode: native
          routingMode: tunnel
        nodeSelector:
          kubernetes.io/os: linux
          pelo.tech/multi-home-networking: "true"
          pelo.tech/uki-labs: "lab3"
