apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nidhogg-system

resources:
  - https://github.com/pelotech/nidhogg//kustomize?ref=v0.5.1

patches:
  - path: overlays/nidhogg-controller-manager.yaml
    target:
      group: apps
      kind: StatefulSet
      name: nidhogg-controller-manager
      version: v1
  - path: overlays/nidhogg-config-patch.yaml
    target:
      kind: ConfigMap
      name: nidhogg-config
