---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.8.3
    helm:
      releaseName: external-dns
      valuesObject:
        txtOwnerId: CLUSTER_NAME
        serviceAccount:
          create: true
          name: external-dns-controller
          annotations:
            eks.amazonaws.com/role-arn: EXTERNAL_DNS_ROLE_ARN
            eks.amazonaws.com/sts-regional-endpoints: "true"
        provider: aws
        policy: sync
        registry: txt
        txtPrefix: xdns-
        resources:
          limits:
            memory: 105M
          requests:
            cpu: 50m
            memory: 105M
  destination:
    namespace: external-dns
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
