apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: admins
    patch: |-
      - op: add
        path: /spec/sourceRepos/-
        value: oci://public.ecr.aws/karpenter/karpenter
      - op: add
        path: /spec/destinations/-
        value:
          namespace: karpenter
          server: https://kubernetes.default.svc

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.KARPENTER_ROLE_ARN
    targets:
      - select:
          version: v1
          kind: ServiceAccount
          name: karpenter
        fieldPaths:
          - metadata.annotations.eks\.amazonaws\.com/role-arn
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: karpenter
        fieldPaths:
          - spec.source.helm.parameters.[name=settings.clusterName].value
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.CLUSTER_ENDPOINT
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: karpenter
        fieldPaths:
          - spec.source.helm.parameters.[name=settings.clusterEndpoint].value # TODO: check if there's a better way to provide values to kustomize from terraform state output
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: karpenter
        fieldPaths:
          - spec.source.helm.parameters.[name=settings.interruptionQueue].value

