apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: admins
    patch: |-
      - op: add
        path: /spec/sourceRepos/-
        value: public.ecr.aws/karpenter
      - op: add
        path: /spec/destinations/-
        value:
          namespace: karpenter
          server: https://kubernetes.default.svc
      - op: add
        path: /spec/destinations/-
        value:
          namespace: kube-node-lease
          server: https://kubernetes.default.svc

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.KARPENTER_ROLE_ARN
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: karpenter
        fieldPaths:
          - spec.source.helm.parameters.0.value # TODO: is there a way to use the [name=serviceAccount.annotations.eks\.amazonaws\.com/role-arn] escapes don't work

  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: karpenter
        fieldPaths:
          - spec.source.helm.parameters.[name=settings.clusterName].value
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: karpenter
        fieldPaths:
          - spec.source.helm.parameters.[name=settings.interruptionQueue].value

