---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: karpenter
    name: in-cluster
  syncPolicy:
    automated: {}
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: v0.32.1
    helm:
      releaseName: karpenter
      parameters:
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: KARPENTER_ROLE_ARN
        - name: serviceAccount.annotations.eks\.amazonaws\.com/sts-regional-endpoints
          value: "true"
          forceString: true
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: "karpenter"
        - name: settings.clusterName
          value: CLUSTER_NAME
        - name: settings.interruptionQueue
          value: CLUSTER_NAME
