---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  destination:
    namespace: karpenter
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  sources:
    - chart: karpenter-crd
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.7.1
      helm:
        valuesObject:
          webhook:
            serviceNamespace: karpenter
    - chart: karpenter
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.7.1
      helm:
        releaseName: karpenter
        skipCrds: true
        valuesObject:
          hostNetwork: true
          controller:
            image:
              digest: >-
                sha256:dac90460a132306d9b4d0531ff30eb5180600e49e519b800352fcaf00d008231
              repository: ghcr.io/pelotech/karpenter
              tag: v1.7.1x
            env:
              - name: IGNORED_NODE_SELECTOR_REQUIREMENTS
                value: scheduling.node.kubevirt.io/tsc-frequency-*
          serviceAccount:
            create: "true"
            name: "karpenter"
            annotations:
              eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN
              eks.amazonaws.com/sts-regional-endpoints: "true"
          settings:
            clusterName: CLUSTER_NAME
            interruptionQueue: CLUSTER_NAME
            featureGates:
              spotToSpotConsolidation: true
              nodeRepair: true
              nodeOverlay: true
          webhook:
            enabled: true
