---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  destination:
    namespace: karpenter
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  sources:
    - chart: karpenter-crd
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.9.0
      helm:
        valuesObject:
          webhook:
            serviceNamespace: karpenter
    - chart: karpenter
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.8.3
      helm:
        releaseName: karpenter
        skipCrds: true
        valuesObject:
          hostNetwork: true
          controller:
            metrics:
              port: 7080
            healthProbe:
              port: 7081
            image:
              digest: >-
                sha256:ea11403256b010678d79d41e5e480143b3f455cfba6d5fa49bb81121ee5ec7e0
              repository: ghcr.io/pelotech/karpenter
              tag: v1.8.3x
            env:
              - name: IGNORED_NODE_SELECTOR_REQUIREMENTS
                value: scheduling.node.kubevirt.io/tsc-frequency-*
          serviceAccount:
            create: "true"
            name: "karpenter"
            annotations:
              eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN
              eks.amazonaws.com/sts-regional-endpoints: "true"
          settings:
            clusterName: CLUSTER_NAME
            interruptionQueue: CLUSTER_NAME
            featureGates:
              spotToSpotConsolidation: true
              nodeRepair: true
              nodeOverlay: true
          webhook:
            enabled: true
