---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: karpenter
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: 0.37.0
    helm:
      releaseName: karpenter
      valuesObject:
        hostNetwork: true
        controller:
          image:
            repository: ghcr.io/pelotech/karpenter
            tag: v0.37.0-modified
            digest: sha256:33fc346aede9002680b95a3c6273a138b2563720308221a6bb5d4659821ec181
          env:
            - name: IGNORED_RESOURCE_REQUESTS
              value: "devices.kubevirt.io/kvm,devices.kubevirt.io/tun,devices.kubevirt.io/vhost-net"
        serviceAccount:
          create: "true"
          name: "karpenter"
          annotations:
            eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN
            eks.amazonaws.com/sts-regional-endpoints: "true"
        settings:
          clusterName: CLUSTER_NAME
          interruptionQueue: CLUSTER_NAME
        webhook:
          enabled: true
