---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  destination:
    namespace: karpenter
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  sources:
    - chart: karpenter-crd
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.7.1
      helm:
        valuesObject:
          webhook:
            serviceNamespace: karpenter
    - chart: karpenter
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.7.1
      helm:
        releaseName: karpenter
        skipCrds: true
        valuesObject:
          hostNetwork: true
          serviceAccount:
            create: "true"
            name: "karpenter"
            annotations:
              eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN
              eks.amazonaws.com/sts-regional-endpoints: "true"
          settings:
            clusterName: CLUSTER_NAME
            interruptionQueue: CLUSTER_NAME
            featureGates:
              spotToSpotConsolidation: true
              nodeRepair: true
              nodeOverlay: true
          webhook:
            enabled: true
