---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: karpenter
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  sources:
    - chart: karpenter-crd
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.1.0
      helm:
        valuesObject:
          webhook:
            serviceNamespace: karpenter
    - chart: karpenter
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.1.0
      helm:
        releaseName: karpenter
        skipCrds: true
        valuesObject:
          hostNetwork: true
          controller:
            image:
              repository: ghcr.io/pelotech/karpenter
              tag: v1.1.0x
              digest: sha256:3645fdf0434b550883d6d7fdc7c9ecfb003809105fd0f180bf3d1a9e858ebc60
            env:
              - name: IGNORED_RESOURCE_REQUESTS
                value: "devices.kubevirt.io/kvm,devices.kubevirt.io/tun,devices.kubevirt.io/vhost-net"
              - name: IGNORED_NODE_SELECTOR_REQUIREMENTS
                value: "scheduling.node.kubevirt.io/tsc-frequency-*"
          serviceAccount:
            create: "true"
            name: "karpenter"
            annotations:
              eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN
              eks.amazonaws.com/sts-regional-endpoints: "true"
          settings:
            clusterName: CLUSTER_NAME
            interruptionQueue: CLUSTER_NAME
          webhook:
            enabled: true
