---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  destination:
    namespace: karpenter
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  sources:
    - chart: karpenter-crd
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.3.3
      helm:
        valuesObject:
          webhook:
            serviceNamespace: karpenter
    - chart: karpenter
      repoURL: public.ecr.aws/karpenter
      targetRevision: 1.7.1
      helm:
        releaseName: karpenter
        skipCrds: true
        valuesObject:
          hostNetwork: true
          controller:
            image:
              repository: ghcr.io/pelotech/karpenter
              tag: v1.3.3x
              digest: sha256:cf08da0b22d1aa4d563a0375e65cdfea4cf9c9abfcd219c580ca1f5b54a6de7e
            env:
              - name: IGNORED_RESOURCE_REQUESTS
                value: "devices.kubevirt.io/kvm,devices.kubevirt.io/tun,devices.kubevirt.io/vhost-net"
              - name: IGNORED_NODE_SELECTOR_REQUIREMENTS
                value: "scheduling.node.kubevirt.io/tsc-frequency-*"
          serviceAccount:
            create: "true"
            name: "karpenter"
            annotations:
              eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN
              eks.amazonaws.com/sts-regional-endpoints: "true"
          settings:
            clusterName: CLUSTER_NAME
            interruptionQueue: CLUSTER_NAME
            featureGates:
              spotToSpotConsolidation: true
              nodeRepair: true
          webhook:
            enabled: true
