---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter
  namespace: karpenter
  annotations:
    eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: karpenter
    name: in-cluster
  syncPolicy:
    automated: {}
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: v0.33.0
    helm:
      releaseName: karpenter
      parameters:
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: "karpenter"
        - name: settings.clusterName
          value: CLUSTER_NAME
        - name: settings.interruptionQueue
          value: CLUSTER_NAME
