---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-driver
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: EBS_CSI_ROLE_ARN
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi-driver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  sources:
  - repoURL: 'https://github.com/pelotech/foundation'
    path: 'gitops/base-install/ebs-csi-driver/snapshot-controller'
    targetRevision: main
  - chart: aws-ebs-csi-driver
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: 2.26.0
    helm:
      releaseName: aws-ebs-csi-driver
      values: |
        storageClasses:
        - name: gp3 
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
          volumeBindingMode: WaitForFirstConsumer
          reclaimPolicy: Delete
          parameters:
            type: gp3
          # TODO: Encrypting volumes by default seems desirable, but may have unintended consequences
          #     encrypted: "true"
        volumeSnapshotClasses:
        - name: gp3
          annotations:
            snapshot.storage.kubernetes.io/is-default-class: "true"
          deletionPolicy: Delete
      parameters:
        - name: controller.serviceAccount.create
          value: "false"
        - name: controller.serviceAccount.name
          value: "ebs-csi-driver"
        - name: controller.resources.limits.memory
          value: "128Mi"
        - name: controller.resources.requests.cpu
          value: "100m"
        - name: controller.resources.requests.memory
          value: "128Mi"
        - name: node.serviceAccount.create
          value: "false"
        - name: node.serviceAccount.name
          value: "ebs-csi-driver"
        - name: node.resources.limits.memory
          value: "128Mi"
        - name: node.resources.requests.cpu
          value: "100m"
        - name: node.resources.requests.memory
          value: "128Mi"
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated: {}
