apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: admins
    patch: |-
      - op: add
        path: /spec/sourceRepos/-
        value: https://fluent.github.io/helm-charts
      - op: add
        path: /spec/destinations/-
        value:
          namespace: fluent-bit
          server: https://kubernetes.default.svc

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.FLUENT_BIT_ROLE_ARN
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: fluent-bit
        fieldPaths:
          - spec.source.helm.parameters.0.value # TODO: is there a way to use the [name=serviceAccount.annotations.eks\.amazonaws\.com/role-arn] escapes don't work

