---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nidhogg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated: {}
  source:
    repoURL: 'https://github.com/pelotech/foundation'
    path: 'gitops/components/nidhogg/kustomize'
    targetRevision: main
