---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: IMAGE_UPDATER_ROLE_ARN
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated: {}
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.9.1
    helm:
      values: |
        # guide: https://github.com/argoproj-labs/argocd-image-updater/issues/112#issuecomment-1058465942
        config:
          registries:
          - name: ECR
            api_url: https://530052405138.dkr.ecr.us-gov-west-1.amazonaws.com
            prefix: 530052405138.dkr.ecr.us-gov-west-1.amazonaws.com
            default: true
            ping: yes
            insecure: no
            credentials: ext:/scripts/ecr-login.sh
            credsexpire: 6h
        extraEnv:
          - name: AWS_REGION
            value: us-gov-west-1
        authScripts:
          enabled: true
          scripts:
            ecr-login.sh: |
              #!/bin/sh
              aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
        resources:
          limits:
            memory: 105M
          requests:
            cpu: 15m
            memory: 105M
        serviceAccount:
          create: false
          name: argocd-image-updater
