apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# Needs azure/disk-csi for the disk.csi.azure.com driver.
components:
  - ../../kubevirt
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: kubevirt
    patch: |-
      - op: replace
        path: /spec/source/path
        value: gitops/components/azure/kubevirt/kustomize
