---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.9.0
    helm:
      releaseName: metrics-server
      values: |
        image:
          tag: v0.6.3
        defaultArgs:
          - --cert-dir=/tmp
          - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
          - --kubelet-use-node-status-port
          - --metric-resolution=35s
        resources:
          limits:
            memory: 105M
          requests:
            cpu: 15m
            memory: 105M
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  source:
    chart: cluster-autoscaler
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.29.4
    helm:
      releaseName: cluster-autoscaler
      parameters:
        - name: rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: AUTOSCALER_ROLE_ARN
        - name: rbac.serviceAccount.annotations.eks\.amazonaws\.com/sts-regional-endpoints
          value: "true"
          forceString: true
        - name: autoDiscovery.clusterName
          value: CLUSTER_NAME
        - name: autoDiscovery.cloudProvider
          value: "aws"
        - name: awsRegion
          value: AWS_REGION
        - name: rbac.serviceAccount.create
          value: "true"
        - name: rbac.serviceAccount.name
          value: "cluster-autoscaler"
        - name: extraArgs.expander
          value: "priority"
        - name: resources.limits.memory
          value: "105M"
        - name: resources.requests.memory
          value: "105M"
        - name: resources.requests.cpu
          value: "15m"
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    20:
      - main.*
    10:
      - fallback.*
