---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: storage
  sources:
  - repoURL: 'https://github.com/pelotech/foundation'
    path: 'gitops/base-install/ebs-csi/snapshot-controller'
    targetRevision: v2.9.10 # x-release-please-version
  - chart: aws-ebs-csi-driver
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: 2.54.1
    helm:
      # TODO: figure out correct roles for controller vs node
      releaseName: aws-ebs-csi-driver
      valuesObject:
        controller:
          k8sTagClusterId: CLUSTER_NAME
          serviceAccount:
            create: true
            name: ebs-csi-driver
            annotations:
              eks.amazonaws.com/role-arn: EBS_CSI_ROLE_ARN
              eks.amazonaws.com/sts-regional-endpoints: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
        node:
          serviceAccount:
            create: false
            name: "ebs-csi-driver"
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "128Mi"
        storageClasses:
          - name: gp3
            allowVolumeExpansion: true
            parameters:
              type: gp3
#              encrypted: "true" #TODO: Encrypting volumes by default seems desirable, check side effects
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
        volumeSnapshotClasses:
          - name: ebs-snapshot
            annotations:
              snapshot.storage.kubernetes.io/is-default-class: "true"
            deletionPolicy: Delete
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated: {}
