---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  sources:
  - repoURL: 'https://github.com/pelotech/foundation'
    path: 'gitops/base-install/ebs-csi/snapshot-controller'
    targetRevision: main
  - chart: aws-ebs-csi-driver
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: 2.27.0
    helm:
      releaseName: aws-ebs-csi-driver
      valuesObject:
        controller:
          serviceAccount:
            create: "true"
            name: ebs-csi-driver
            annotations:
              eks.amazonaws.com/role-arn: EBS_CSI_ROLE_ARN
              eks.amazonaws.com/sts-regional-endpoints: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
        node:
          serviceAccount:
            create: "false"
            name: "ebs-csi-driver"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
        storageClasses:
          - name: gp3
            parameters:
              type: gp3
#              encrypted: "true" #TODO: Encrypting volumes by default seems desirable, check side effects
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
          - name: gp2
            parameters:
              type: gp2
#              encrypted: "true" #TODO: Encrypting volumes by default seems desirable, check side effects
        volumeSnapshotClasses:
          - name: ebs-snapshot
            annotations:
              snapshot.storage.kubernetes.io/is-default-class
            deletionPolicy: Delete
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated: {}
