apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Needs the external-dns-azure Secret in the external-dns namespace, see README.md.
components:
  - ../../external-dns

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: external-dns
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: external-dns
      spec:
        source:
          helm:
            valuesObject:
              provider:
                name: azure
              podLabels:
                azure.workload.identity/use: "true"
              serviceAccount:
                annotations:
                  azure.workload.identity/client-id: EXTERNAL_DNS_CLIENT_ID
              extraVolumes:
                - name: azure-config-file
                  secret:
                    secretName: external-dns-azure
              extraVolumeMounts:
                - name: azure-config-file
                  mountPath: /etc/kubernetes
                  readOnly: true

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.EXTERNAL_DNS_CLIENT_ID
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: external-dns
        fieldPaths:
          - spec.source.helm.valuesObject.serviceAccount.annotations.[azure.workload.identity/client-id]
