apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
spec:
  template:
    spec:
      containers:
        - name: kube-multus
          args:
            - "--multus-conf-file=auto"
            - "--cni-version=0.4.0"
            - "--multus-master-cni-file-name=10-aws.conflist"
            - "--multus-log-level=error"
            - "--multus-log-file=/var/log/aws-routed-eni/multus.log"
