apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
spec:
  template:
    spec:
      containers:
        - name: kube-multus
          startupProbe:
            exec:
              command:
                - cat
                - /etc/cni/net.d/10-aws.conflist
