apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      # TODO: once nginx ingress migration is complete, EG_NLB_NAME can be replaced with CLUSTER_NAME
      fieldPath: data.EG_NLB_NAME
    targets:
      - select:
          group: gateway.envoyproxy.io
          version: v1alpha1
          kind: EnvoyProxy
          name: eg-proxy
        fieldPaths:
          - spec.provider.kubernetes.envoyService.annotations.[service.beta.kubernetes.io/aws-load-balancer-name]
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.EG_REPO_URL
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: envoy-gateway
        fieldPaths:
          - spec.source.repoURL
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.EG_TARGET_REVISION
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: envoy-gateway
        fieldPaths:
          - spec.source.targetRevision
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.EG_GATEWAY_IMAGE
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: envoy-gateway
        fieldPaths:
          - spec.source.helm.valuesObject.global.images.envoyGateway.image
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.EG_RATELIMIT_IMAGE
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: envoy-gateway
        fieldPaths:
          - spec.source.helm.valuesObject.global.images.ratelimit.image
