---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  sources:
    - chart: gateway-helm
      repoURL: docker.io/envoyproxy
      targetRevision: v1.8.0
      helm:
        releaseName: envoy-gateway
    - repoURL: "https://github.com/pelotech/foundation"
      path: gitops/components/envoy-gateway/create-gateway
      targetRevision: v4.5.3 # x-release-please-version
      helm:
        releaseName: create-gateway
        valuesObject:
          nlbName: EG_NLB_NAME
  destination:
    namespace: envoy-gateway-system
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    automated: {}
