apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v6.3.3
  - https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v6.3.3

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"

patches:
- target:
    group: apps
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/tolerations
      value:
      - key: CriticalAddonsOnly
        operator: Exists
