---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
  labels:
    {{- include "create-issuer.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.acmeIssuerEmail }}
    privateKeySecretRef:
      name: {{ .Values.issuerName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingressClassName }}
      - dns01:
          route53:
            region: {{ .Values.awsRegion }}
        selector:
          matchLabels:
            "use-dns01-solver": "true"
