apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: admins
    patch: |-
      - op: add
        path: /spec/destinations/-
        value:
          namespace: tailscale
          server: https://kubernetes.default.svc

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.VPC_CIDR_BLOCK
    targets:
      - select:
          version: v1
          kind: Deployment
          name: tailscale
        fieldPaths:
          - spec.template.spec.containers.[name=tailscale].env.[name=TS_ROUTES].value
