apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/multus/v3.9.2-eksbuild.1/aws-k8s-multus.yaml
  - ./nidhogg

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: kube-multus-ds
    path: ./overlays/multus-daemonset-patch.yaml
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: kube-multus-ds
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --readiness-indicator-file=/etc/cni/net.d/10-aws.conflist

