---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  destination:
    namespace: reloader
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 2.2.5
    helm:
      releaseName: reloader
      valuesObject:
        reloader:
          reloadStrategy: annotations
          deployment:
            resources:
              limits:
                memory: 105M
              requests:
                cpu: 15m
                memory: 105M
