apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # renovate: datasource=github-releases packageName=k8snetworkplumbingwg/multus-cni
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/refs/tags/v4.3.0/deployments/multus-daemonset-thick.yml

images:
  - name: ghcr.io/k8snetworkplumbingwg/multus-cni
    newTag: v4.3.1-thick@sha256:a357a79359b80ddd5f4699117946cacf3b54f5baecf7944535594863e875fc25

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: kube-multus-ds
    path: overlays/multus-daemonset.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: multus-daemon-config
    path: overlays/multus-configmap.yaml
