resources:
  - ./resources.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/aws/deploy.yaml

patches:
  - path: overlays/ingress-class-nginx-patch.yaml
    target:
      kind: IngressClass
      name: nginx
  - path: overlays/ingress-nginx-controller-service.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
  - path: overlays/nginx-ingress-controller-patch.yaml
    target:
      group: apps
      kind: Deployment
      name: ingress-nginx-controller
      version: v1
  - path: overlays/nginx-ingress-config-patch.yaml
    target:
      kind: ConfigMap
      name: ingress-nginx-controller
