apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: admins
    patch: |-
      - op: add
        path: /spec/sourceRepos/-
        value: https://grafana.github.io/helm-charts
      - op: add
        path: /spec/destinations/-
        value:
          namespace: loki
          server: https://kubernetes.default.svc

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.LOKI_ROLE_ARN
    targets:
      - select:
          version: v1
          kind: ServiceAccount
          name: loki
        fieldPaths:
          - metadata.annotations.eks\.amazonaws\.com/role-arn
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.AWS_REGION
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: loki
        fieldPaths:
          - spec.source.helm.parameters.[name=storage.s3.region].value
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.LOKI_S3_BUCKET
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: loki
        fieldPaths:
          - spec.source.helm.parameters.[name=storage.bucketNames.chunks].value
          - spec.source.helm.parameters.[name=storage.bucketNames.ruler].value
          - spec.source.helm.parameters.[name=storage.bucketNames.admin].value
