apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.LOKI_ROLE_ARN
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: loki
        fieldPaths:
          - spec.source.helm.valuesObject.serviceAccount.annotations.[eks.amazonaws.com/role-arn]

  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.AWS_REGION
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: loki
        fieldPaths:
          - spec.source.helm.valuesObject.loki.storage.s3.region
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.LOKI_S3_BUCKET
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: loki
        fieldPaths:
          - spec.source.helm.valuesObject.loki.storage.bucketNames.chunks
          - spec.source.helm.valuesObject.loki.storage.bucketNames.ruler
          - spec.source.helm.valuesObject.loki.storage.bucketNames.admin
  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.LOKI_GATEWAY_HOST
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: loki
        fieldPaths:
          - spec.source.helm.valuesObject.gateway.ingress.hosts.0.host
          - spec.source.helm.valuesObject.gateway.ingress.tls.0.hosts.0
