---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: loki
  annotations:
    eks.amazonaws.com/role-arn: LOKI_ROLE_ARN
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  destination:
    namespace: loki
    name: in-cluster
  syncPolicy:
    automated: {}
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.8.0
    helm:
      releaseName: loki
      parameters:
        - name: storage.s3.region
          value: AWS_REGION
        - name: storage.bucketNames.chunks
          value: LOKI_S3_BUCKET
        - name: storage.bucketNames.ruler
          value: LOKI_S3_BUCKET
        - name: storage.bucketNames.admin
          value: LOKI_S3_BUCKET
      values: |
        serviceAccount:
          create: false
          name: loki
        singleBinary:
          replicas: 2
          persistence:
            enabled: false
            enableStatefulSetAutoDeletePVC: false
          # https://github.com/grafana/loki/issues/6370
          extraArgs:
            - -config.expand-env=true
          extraEnv:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        write:
          replicas: 0
        read:
          replicas: 0
        backend:
          replicas: 0
        loki:
          extraMemberlistConfig:
            bind_addr:
              - ${MY_POD_IP}
          auth_enabled: false
          commonConfig:
            path_prefix: /tmp/loki
            replication_factor: 2
          storage_config:
            boltdb_shipper:
              shared_store: s3
          compactor:
            retention_enabled: true
            shared_store: s3
          limits_config:
            retention_period: 720h
        gateway:
          enabled: false
        ingress:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          serviceMonitor:
            enabled: false
          dashboards:
            enabled: false
          rules:
            enabled: false
          lokiCanary:
            enabled: false
        test:
          # Depends on selfMonitoring.enabled
          enabled: false
