- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      memory: 750Mi
    requests:
      cpu: 500m
      memory: 750Mi
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: CriticalAddonsOnly
      operator: Exists
