---
- {op: add, path: /rules/3/verbs/-, value: create}
- {op: add, path: /rules/3/verbs/-, value: update}
- {op: add, path: /rules/-, value: { apiGroups: [""], resources: ["pod/exec"], verbs: ["create"]}}
