- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: CriticalAddonsOnly
      operator: Exists
