- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      memory: 164M
    requests:
      cpu: 15m
      memory: 164M
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: CriticalAddonsOnly
      operator: Exists
