---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapscheduler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: storage
  destination:
    namespace: snapscheduler
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  source:
    chart: snapscheduler
    repoURL: https://backube.github.io/helm-charts
    targetRevision: 3.4.0
    helm:
      releaseName: snapscheduler
