apiVersion: v1
data:
  config.json: |
    {
      "taintNamePrefix": "nidhogg.uswitch.com",
      "taintRemovalDelayInSeconds": 10,
      "nodeSelector": [
        "kubernetes.io/os=linux"
      ],
      "daemonsets": [
        {
          "name": "kube-multus-ds",
          "namespace": "kube-system"
        }
      ]
    }
kind: ConfigMap
metadata:
  name: nidhogg-config
  namespace: nidhogg-system
