apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/labels
        value: {goldilocks.fairwinds.com/enabled: "true"}
