---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: goldilocks
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: admins
  source:
    chart: goldilocks
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: 6.5.5
    helm:
      releaseName: goldilocks
      values: |
        controller:
          flags:
            on-by-default: true
          resources:
            requests:
              cpu: 15m
              memory: 105M
            limits:
              memory: 105M
        dashboard:
          resources:
            requests:
              cpu: 15m
              memory: 105M
            limits:
              memory: 105M
        vpa:
          enabled: true
  destination:
    namespace: goldilocks
    name: in-cluster
  syncPolicy:
    automated: {}
