---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  source:
    chart: goldilocks
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: 6.8.0
    helm:
      releaseName: goldilocks
      valuesObject:
        controller:
          flags:
            on-by-default: true
          resources:
            requests:
              cpu: 15m
              memory: 105M
            limits:
              memory: 105M
        dashboard:
          resources:
            requests:
              cpu: 15m
              memory: 105M
            limits:
              memory: 105M
        vpa:
          enabled: true
  destination:
    namespace: goldilocks
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
