# CPU avg 1.2% of 4vCPU  = .048 ~= 50m
# Memory max 256 megs
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: CriticalAddonsOnly
      operator: Exists
