- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      memory: 150Mi
    requests:
      cpu: 5m
      memory: 150Mi
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: CriticalAddonsOnly
      operator: Exists
