apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.1.0/kubevirt-cr.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.1.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/common-instancetypes/VirtualMachineClusterInstancetypes
  - https://github.com/kubevirt/common-instancetypes/VirtualMachineClusterPreferences
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.57.0/cdi-cr.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.57.0/cdi-operator.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: admins
    patch: |-
      - op: add
        path: /spec/destinations/-
        value:
          namespace: kubevirt
          server: https://kubernetes.default.svc
      - op: add
        path: /spec/destinations/-
        value:
          namespace: cdi
          server: https://kubernetes.default.svc
  - target:
      group: kubevirt.io
      version: v1
      kind: KubeVirt
      name: kubevirt
      namespace: kubevirt
    patch: |-
      - op: add
        path: /spec/configuration/developerConfiguration/useEmulation
        value: true

