apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubevirt/kubevirt/releases/download/v1.1.0/kubevirt-cr.yaml
- https://github.com/kubevirt/kubevirt/releases/download/v1.1.0/kubevirt-operator.yaml
- https://github.com/kubevirt/common-instancetypes/VirtualMachineClusterInstancetypes
- https://github.com/kubevirt/common-instancetypes/VirtualMachineClusterPreferences

patches:
  - patch: |-
      - op: add
        path: /spec/configuration/developerConfiguration/useEmulation
        value: true
    target:
      kind: kubevirt
      name: kubevirt
      namespace: kubevirt
