apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: admins
    patch: |-
      - op: add
        path: /spec/destinations/-
        value:
          namespace: kubevirt
          server: https://kubernetes.default.svc
      - op: add
        path: /spec/destinations/-
        value:
          namespace: cdi
          server: https://kubernetes.default.svc
  - target:
      group: kubevirt.io
      version: v1
      kind: KubeVirt
      name: kubevirt
      namespace: kubevirt
    patch: |-
      - op: add
        path: /spec/configuration/developerConfiguration/useEmulation
        value: true
      - op: add
        path: /spec/workloads/nodePlacement/tolerations/-
        value:
          key: pelo.tech/multi-home-networking
          operator: Exists
      - op: add
        path: /spec/workloads/nodePlacement/tolerations/-
        value:
          key: pelo.tech/uki-labs
          operator: Exists
