---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  destination:
    namespace: kubevirt
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  source:
    repoURL: 'https://github.com/pelotech/foundation'
    path: 'gitops/components/kubevirt/kustomize'
    targetRevision: v3.0.1 # x-release-please-version
