---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.2
    helm:
      releaseName: cert-manager
      valuesObject:
        installCRDs: true
        serviceAccount:
          create: true
          name: cert-manager
          annotations:
            eks.amazonaws.com/role-arn: CERT_MANAGER_ROLE_ARN
            eks.amazonaws.com/sts-regional-endpoint: "'true'"
        extraEnv:
          - name: AWS_REGION
            value: "us-east-1"
        securityContext:
          fsGroup: 1001
        resources:
          requests:
            cpu: "15m"
            memory: "105M"
          limits:
            cpu: "15m"
            memory: "105M"
        webhook:
          hostNetwork: true
          securePort: 10251
          resources:
            requests:
              cpu: "15m"
              memory: "105M"
            limits:
              cpu: "15m"
              memory: "105M"
        cainjector:
          resources:
            requests:
              cpu: "15m"
              memory: "105M"
            limits:
              cpu: "15m"
              memory: "105M"
  destination:
    namespace: cert-manager
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-issuer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    repoURL: 'https://github.com/pelotech/foundation'
    path: gitops/base-install/cert-manager/create-issuer
    helm:
      releaseName: create-issuer
      valuesObject:
        acmeIssuerEmail: ACME_ISSUER_EMAIL
        awsRegion: AWS_REGION
    targetRevision: v2.4.0 # x-release-please-version
  destination:
    namespace: cert-manager
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
